// 금융 용어 플래시카드 — Part 2 (7~12주차 용어)
window.TERMS = (window.TERMS || []).concat([
// 7주차
{ id:"per", ko:"주가수익비율", en:"P/E Ratio", week:7, def:"주가 ÷ EPS = 시총 ÷ 순이익. 이익의 몇 배를 주고 사는가. 높다 ≠ 비싸다 — 성장률·ROIC·리스크·지속기간의 함수.", hint:"멀티플 = 시장이 미래에 매긴 가격" },
{ id:"forwardpe", ko:"선행 PER", en:"Forward P/E", week:7, def:"내년 예상 이익 기준 PER. 성장주는 선행으로 본다. 후행(Trailing)은 지난 12개월 실제 이익.", hint:"성장주는 선행" },
{ id:"earningsyield", ko:"이익수익률", en:"Earnings Yield", week:7, def:"PER의 역수 = 순이익 ÷ 시총. PER 20 = 5%. 국채 금리와 비교 가능.", hint:"PER 20 = 5%" },
{ id:"peg", ko:"PEG", en:"PEG Ratio", week:7, def:"PER ÷ 이익성장률. 피터 린치 경험칙: 1 이하 싸고 2 이상 비쌈. 조잡하지만 성장 대비 가격의 첫 감각.", hint:"PER 30 / 성장 30 = 1.0" },
{ id:"multiplecompression", ko:"멀티플 압축", en:"Multiple Compression", week:7, def:"같은 이익에 시장이 더 낮은 배수를 주는 것. 성장 기대 하락·금리 상승이 원인. 반대는 멀티플 확장.", hint:"기대 하락 → 압축" },
{ id:"psr", ko:"주가매출비율", en:"P/S Ratio", week:7, def:"시총 ÷ 매출. 적자 성장주의 지표. 마진을 무시하므로 EV/매출총이익으로 보정. 금리에 가장 민감한 멀티플.", hint:"마진 무시 — 보정 필요" },
{ id:"evebitda", ko:"EV/EBITDA", en:"EV/EBITDA", week:7, def:"자본구조·세율·감가상각 정책이 다른 회사를 공정 비교. M&A와 자본집약 산업의 표준 언어. CapEx 무시하므로 EV/FCF와 함께.", hint:"M&A의 언어" },
{ id:"evfcf", ko:"EV/FCF", en:"EV/FCF", week:7, def:"가장 정직한 멀티플. 회계 조정이 가장 적다. SBC를 뺀 FCF로 다시 계산하는 습관.", hint:"가장 정직" },
{ id:"evgrossprofit", ko:"EV/매출총이익", en:"EV / Gross Profit", week:7, def:"PSR의 마진 보정 버전. 같은 PSR이라도 마진이 2배면 실질 가격은 절반.", hint:"PSR 보정판" },
{ id:"multipledrivers", ko:"멀티플의 4요소", en:"Multiple Drivers", week:7, def:"정당한 멀티플 = f(성장률, ROIC, 리스크, 지속기간). 이 4가지로 설명되는 격차는 정당하고, 설명 안 되는 격차가 기회 또는 함정.", hint:"성장·ROIC·리스크·지속" },
{ id:"durability", ko:"성장의 지속기간", en:"Durability", week:7, def:"초과 성장이 얼마나 오래 지속되는가. 시장이 '얼마나 오래 믿는가'가 프리미엄의 대부분. 해자가 이를 지킨다.", hint:"20% 성장 3년 vs 15년" },
{ id:"discountrate", ko:"할인율", en:"Discount Rate", week:7, def:"미래 현금을 현재가치로 바꿀 때 쓰는 요구수익률. 무위험 금리 + 리스크 프리미엄. 오르면 모든 자산 가치가 내려간다.", hint:"자산 가격의 중력" },
{ id:"expectationsinvesting", ko:"기대치 투자", en:"Expectations Investing", week:7, def:"'얼마짜리인가' 대신 '현재 가격이 정당화되려면 무엇을 해내야 하나'를 역산. 예측보다 가정의 현실성 판단이 쉽다.", hint:"모부신 — 가격에서 역산" },
{ id:"guidance", ko:"가이던스", en:"Guidance", week:7, def:"회사가 제시하는 향후 실적 전망. 보수적으로 주고 넘기는 패턴이 정석. 상향/유지/하향 방향이 주가를 움직인다.", hint:"살짝 낮게 주고 넘기기" },
{ id:"priced_in", ko:"가격 반영", en:"Priced In", week:7, def:"어떤 정보·기대가 이미 주가에 들어 있는 것. 좋은 회사와 좋은 투자가 다른 이유 — 모두가 아는 좋음은 가격에 다 들어 있다.", hint:"좋은 회사 ≠ 좋은 투자" },
{ id:"valuationcard", ko:"밸류에이션 카드", en:"Valuation Card", week:7, def:"종목별 한 장: 가격, 멀티플, 역사적 범위, 동종 비교, 반영된 기대, 내 판단, 판단이 바뀌는 조건. 분기마다 갱신하는 판단의 기록.", hint:"7번(바뀌는 조건)이 핵심" },
{ id:"thesis", ko:"투자 논지", en:"Investment Thesis", week:7, def:"이 회사를 보유하는 이유와 그것이 틀렸음을 알려줄 신호를 담은 한 페이지. 반증 조건 없는 논지는 검증 불가.", hint:"반증 조건 필수" },
// 8주차
{ id:"timevalue", ko:"돈의 시간가치", en:"Time Value of Money", week:8, def:"오늘의 100만 원 > 내년의 100만 원. 지금 쓸 수 있고, 불릴 수 있고, 못 받을 위험이 있으니까. 그래서 미래 돈은 할인한다.", hint:"현재가치 = 미래 ÷ (1+r)^n" },
{ id:"presentvalue", ko:"현재가치", en:"Present Value", week:8, def:"미래 금액 ÷ (1 + 할인율)^년수. 할인율 10%면 10년 뒤 100은 오늘 38.6. 할인율 2배면 10년 뒤 돈은 거의 반토막.", hint:"10%·10년 → 38.6%" },
{ id:"riskfreerate", ko:"무위험 금리", en:"Risk-Free Rate", week:8, def:"미국 10년 국채 금리. 모든 자산 밸류에이션의 기준선. 주식은 이보다 얼마나 더 벌어줘야 하는가(리스크 프리미엄).", hint:"10년물 국채" },
{ id:"riskpremium", ko:"리스크 프리미엄", en:"Risk Premium", week:8, def:"무위험 금리 위에 위험 감수 대가로 추가 요구하는 수익률. 안정 대형주 4~5%, 고위험 성장주 7~10%.", hint:"할인율 = 무위험 + 프리미엄" },
{ id:"dcf", ko:"현금흐름할인법", en:"DCF (Discounted Cash Flow)", week:8, def:"미래 FCF를 모두 현재가치로 환산해 더한 것. 정확한 숫자가 아니라 '어떤 가정이 가치를 가장 흔드는가'를 알려주는 도구.", hint:"산출물은 숫자가 아니라 민감도" },
{ id:"terminalvalue", ko:"터미널 가치", en:"Terminal Value", week:8, def:"예측 기간 이후 영구 지속되는 가치. DCF 전체의 60~80%. 영구성장법 또는 출구 멀티플법. DCF가 장기 가정에 민감한 이유.", hint:"가치의 60~80%가 10년 뒤 이후" },
{ id:"perpetualgrowth", ko:"영구성장률", en:"Perpetual Growth Rate", week:8, def:"터미널 가치 계산의 영원한 성장률. 장기 명목 GDP 이하(2~3%). 5% 이상은 경제보다 영원히 빨리 큰다는 뜻이라 불가.", hint:"2~3% — GDP 못 넘음" },
{ id:"exitmultiple", ko:"출구 멀티플", en:"Exit Multiple", week:8, def:"터미널 가치를 마지막 해 EBITDA × 정상 멀티플로 구하는 방법. 영구성장법의 대안.", hint:"마지막 해 × 정상 배수" },
{ id:"sensitivity", ko:"민감도 분석", en:"Sensitivity Analysis", week:8, def:"가정을 하나씩 바꿔 가치가 얼마나 변하는지 보는 것. 할인율·영구성장률 1%p가 가치 20~30%를 움직인다. 가장 큰 변수 = 감시할 변수.", hint:"DCF의 진짜 산출물" },
{ id:"scenario", ko:"시나리오 분석", en:"Scenario Analysis", week:8, def:"Bull/Base/Bear 세 미래에 확률을 매겨 기대가치를 구하는 것. 현재 주가가 어느 시나리오를 반영하는지 알 수 있다.", hint:"확률 가중 기대가치" },
{ id:"expectedvalue", ko:"기대가치", en:"Expected Value", week:8, def:"각 시나리오 가치 × 확률의 합. 현재 주가와 비교해 안전마진 여부 판단.", hint:"Σ(가치 × 확률)" },
{ id:"keydriver", ko:"핵심 변수", en:"Key Value Driver", week:8, def:"민감도 분석에서 가치를 가장 크게 흔드는 단 하나의 변수. 분기마다 확인할 유일한 지표. 경영진이 집중해야 할 변수.", hint:"테슬라: 자동차 마진 + 로보택시 이정표" },
{ id:"optionvalue", ko:"옵션 가치", en:"Option Value", week:8, def:"불확실하지만 0으로 놓기엔 큰 신사업의 가치. 성공 확률 × 성공 시 가치. 변동성 클수록, 시간 길수록 크다. 기본 사업 가치와 따로 계산.", hint:"확률 20% × 1,000 = 200" },
{ id:"narrative", ko:"내러티브", en:"Narrative", week:8, def:"이 회사가 무엇이 될 것인가의 이야기. 숫자 없는 이야기는 몽상, 이야기 없는 숫자는 무의미(다모다란). 가능·그럴듯·개연성 3단계로 검증.", hint:"이야기 + 숫자" },
{ id:"milestone", ko:"이정표", en:"Milestone", week:8, def:"이야기가 현실이 되는 중간 점검점. 약속 시점과 실제 시점을 기록. 반복 지연되면 시장은 확률을 낮춘다.", hint:"3년째 '내년'이면 위험" },
{ id:"reversedcf", ko:"역DCF", en:"Reverse DCF", week:8, def:"현재 시총에서 출발해 그것을 정당화하는 성장률을 역산. 그 성장률이 역사적으로 달성된 적 있는지 검증. 비현실적이면 가격에 과도한 기대.", hint:"가격 → 필요 성장률" },
{ id:"investmentthesis", ko:"투자 논지 문서", en:"Investment Thesis Document", week:8, def:"역DCF 워크숍의 산출물. 현재 상태, 시장 가정, 검증, 나의 시나리오, 결론과 감시 변수를 담은 한 페이지.", hint:"알고 보유 vs 모르고 보유" },
{ id:"tam", ko:"총 시장 규모", en:"TAM (Total Addressable Market)", week:8, def:"회사가 노릴 수 있는 시장 전체 크기. 역DCF의 성장률이 현실적인지 검증하는 상한. 회사가 말하는 TAM은 대개 부풀려져 있다.", hint:"10년 뒤 매출이 TAM의 몇 %?" },
// 9주차
{ id:"moat", ko:"해자", en:"Economic Moat", week:9, def:"경쟁자를 막아 높은 ROIC를 장기 유지하게 하는 힘. 무형자산·전환비용·네트워크 효과·원가 우위·효율적 규모. 폭보다 방향이 중요.", hint:"10년 ROIC 20%+ = 해자 있음" },
{ id:"switchingcost", ko:"전환비용", en:"Switching Costs", week:9, def:"바꾸기 귀찮거나 위험해서 고객이 잡혀 있는 것. 기업용 소프트웨어, 은행 계좌. NRR이 높은 이유.", hint:"팔란티어 정부 시스템" },
{ id:"networkeffect", ko:"네트워크 효과", en:"Network Effects", week:9, def:"쓰는 사람이 많을수록 가치가 커지는 것. 플랫폼·결제망·소셜. 1등 독식.", hint:"비자, 에어비앤비" },
{ id:"costadvantage", ko:"원가 우위", en:"Cost Advantage", week:9, def:"같은 것을 더 싸게 만드는 힘. 규모·입지·독점 자원. 테슬라의 '대당 원가'가 노리는 것.", hint:"코스트코, TSMC" },
{ id:"pricingpower", ko:"가격 결정력", en:"Pricing Power", week:9, def:"원가가 올라도 가격을 올리고 고객이 안 떠나는 힘. 해자의 숫자적 증거. 인플레기에 마진을 지키는 유일한 방법.", hint:"버핏: 사업 평가의 단 하나 질문" },
{ id:"outsiderceo", ko:"아웃사이더 CEO", en:"Outsider CEO", week:9, def:"손다이크의 책. 운영보다 자본배분에 집중해 시장을 수십 배 이긴 8명의 CEO. 주가 따라 행동이 바뀌고 기회비용으로 사고한다.", hint:"자본배분의 달인들" },
{ id:"opportunitycost", ko:"기회비용", en:"Opportunity Cost", week:9, def:"이 선택 때문에 포기한 최선의 대안 가치. 자본배분의 기준: 자사주 vs 공장 vs 인수 중 수익률 비교.", hint:"5가지 선택지 비교" },
{ id:"empirebuilding", ko:"제국 건설", en:"Empire Building", week:9, def:"주주가치보다 회사 규모·CEO 위상을 위한 확장. 고점 대형 인수, 저ROIC 성장. 나쁜 자본배분의 전형.", hint:"성장을 위한 성장" },
{ id:"proxy", ko:"위임장 설명서", en:"Proxy Statement (DEF 14A)", week:9, def:"주주총회 전 공시. 경영진 보상 구조·성과 지표·이사회 구성. CEO가 무엇에 보상받는지 보는 유일한 문서.", hint:"멍거: 인센티브를 보여주면 결과를 보여주겠다" },
{ id:"insidertrading", ko:"내부자 거래", en:"Insider Transactions", week:9, def:"임원·이사의 자사 주식 매매. 자기 돈 매수는 가장 강한 신호, 매도는 여러 이유가 있어 약한 신호.", hint:"매수 = 하나의 이유 / 매도 = 여러 이유" },
{ id:"alignment", ko:"이해관계 정렬", en:"Alignment", week:9, def:"경영진 보상·지분이 주주 이익과 같은 방향인가. ROIC·FCF·주당 가치 연동이면 정렬, 매출·EPS만 연동이면 왜곡 가능.", hint:"같은 배에 탔는가" },
{ id:"form4", ko:"Form 4", en:"Form 4", week:9, def:"내부자 거래 공시. 2영업일 내 제출. Code P(공개시장 매수)를 찾아본다.", hint:"내부자 매매 공시" },
{ id:"shareholderletter", ko:"주주서한", en:"Shareholder Letter", week:9, def:"경영진이 주주에게 쓰는 연례 편지. 첫 문단, 강조 지표, 실패 언급, 장기 그림, 자본배분 원칙을 읽는다. 아마존 1997, 버크셔가 기준.", hint:"실패를 어떻게 다루는가" },
{ id:"earningscall", ko:"실적 컨퍼런스콜", en:"Earnings Call", week:9, def:"실적 발표 후 경영진과 애널리스트의 통화. 준비된 발언은 홍보, Q&A가 진짜 정보. 회피 패턴·반복 질문·톤 변화를 듣는다.", hint:"Q&A가 전부" },
{ id:"transcript", ko:"트랜스크립트", en:"Transcript", week:9, def:"컨퍼런스콜 녹취록. 읽는 것이 듣는 것보다 빠르다. IR 페이지·무료 사이트에서 구할 수 있고 튜터에 붙여넣어 분석 가능.", hint:"읽기 > 듣기" },
{ id:"qanda", ko:"Q&A 읽기", en:"Q&A Reading", week:9, def:"회피 패턴('좋은 질문입니다, 큰 그림에서…'), 숫자 회피, 반복 질문(=시장 핵심 우려), 전 분기 대비 톤 변화를 찾는 것.", hint:"'구체적 수치는 공개 않지만' = 나쁜 숫자" },
{ id:"businessmodel", ko:"9칸 사업모델", en:"One-Page Business Model", week:9, def:"고객·가치·매출구조·원가구조·핵심자산·해자·성장엔진·핵심변수·리스크. 각 칸 한두 문장 + 숫자 하나. 뉴스가 어느 칸을 건드리는지로 노이즈 판별.", hint:"CEO가 놀랄 질문 하나를 위한 지도" },
{ id:"keyvariable", ko:"핵심 변수(8칸)", en:"Key Variable", week:9, def:"9칸 중 8번. 가치를 가장 흔드는 1~2개 숫자. 밸류에이션 카드의 감시 변수와 일치해야 한다.", hint:"DCF 민감도에서 나온 것" },
{ id:"noise", ko:"노이즈", en:"Noise", week:9, def:"가격만 흔들고 가치를 바꾸지 않는 정보. 9칸 사업모델의 어느 칸도 건드리지 않는 뉴스.", hint:"칸을 안 건드리면 노이즈" },
// 10주차
{ id:"10k_structure", ko:"10-K 구조", en:"10-K Structure", week:10, def:"Item 1 사업 → Item 1A 리스크 → Item 7 MD&A → Item 8 재무제표+주석 순으로 읽는다. 올해와 작년을 비교해 달라진 문장을 찾는 것이 가장 강력.", hint:"1 → 7 → 8, 그리고 전년 비교" },
{ id:"mdna", ko:"경영진 논의 및 분석", en:"MD&A", week:10, def:"10-K Item 7. 경영진이 매출·비용·현금 변동의 '왜'를 서술. 유동성·자본 자원 섹션에서 부채 약정과 자금 계획을 본다.", hint:"숫자의 '왜'" },
{ id:"notes", ko:"주석", en:"Notes to Financial Statements", week:10, def:"재무제표 뒤의 세부 설명. 매출 인식·세그먼트·부채 만기·주식보상·약정과 우발부채·후속사건. 진짜 정보는 여기 있다.", hint:"본문보다 주석" },
{ id:"materialweakness", ko:"중대한 취약점", en:"Material Weakness", week:10, def:"10-K Item 9A에서 내부통제에 중대 결함이 있다는 고백. 회계 숫자 신뢰성 경고.", hint:"9A에 나오면 경고" },
{ id:"subsequentevents", ko:"후속사건", en:"Subsequent Events", week:10, def:"결산일 이후 보고서 제출 전에 일어난 중요 사건. 주석 마지막에 있다. 대형 인수·소송·자금 조달이 여기 먼저 나온다.", hint:"결산 후 일어난 큰 일" },
{ id:"pressrelease", ko:"실적 보도자료", en:"Earnings Press Release", week:10, def:"실적 발표일 8-K로 제출. 헤드라인 숫자·CEO 코멘트·가이던스·요약 재무제표·GAAP↔Non-GAAP 조정표. 회사가 헤드라인에 올린 숫자와 구석에 놓은 숫자의 배치를 본다.", hint:"조정표를 반드시" },
{ id:"10q", ko:"10-Q", en:"Form 10-Q", week:10, def:"분기 보고서. 감사 아닌 검토. 보도자료에 없는 운전자본·부채·세그먼트 세부와 주석 변화가 있다.", hint:"분기판 10-K, 주석 변화 확인" },
{ id:"whispernumber", ko:"속삭임 숫자", en:"Whisper Number", week:10, def:"공식 컨센서스보다 높은 시장의 실제 기대치. 발표 전 주가 급등이 신호. 컨센서스를 넘어도 속삭임에 못 미치면 하락.", hint:"진짜 기대치" },
{ id:"guidancerevision", ko:"가이던스 조정", en:"Guidance Revision", week:10, def:"회사가 전망을 상향·유지·하향하는 것. 실적 자체보다 주가에 더 큰 영향. 회사의 가이던스 패턴(보수적/공격적)을 8분기 표로 파악.", hint:"결과보다 전망 방향" },
{ id:"8k", ko:"8-K", en:"Form 8-K", week:10, def:"수시 보고. 4영업일 내. Item 1.01 중요 계약, 2.02 실적, 2.03 부채, 5.02 임원 변동(CFO 사임 주목), 7.01 FD 공시.", hint:"1.01 / 5.02가 중요" },
{ id:"form4_codes", ko:"Form 4 코드", en:"Form 4 Transaction Codes", week:10, def:"P = 공개시장 매수(강한 신호), S = 매도(약한 신호), M = 옵션 행사, A = 부여. 10b5-1 계획 매도인지 확인.", hint:"P를 찾아라" },
{ id:"13f", ko:"13F", en:"Form 13F", week:10, def:"1억 달러 이상 기관의 분기 보유 현황. 45일 지연. 유명 투자자 추적과 '누가 같은 배에 있는가' 확인용.", hint:"45일 늦은 정보" },
{ id:"13d", ko:"13D / 13G", en:"Schedule 13D / 13G", week:10, def:"5% 이상 대주주 공시. 13D는 경영 개입 의도(행동주의, 주가 촉매), 13G는 수동 보유(인덱스 펀드).", hint:"D = 개입, G = 수동" },
{ id:"10b51", ko:"10b5-1 계획", en:"Rule 10b5-1 Plan", week:10, def:"내부자가 미리 예약한 자동 매도 계획. 이에 따른 매도는 신호가 약하다. 계획 없는 대량 매도가 실적 전 몰리면 주의.", hint:"예약 매도 = 신호 약함" },
{ id:"revenuerecognition", ko:"매출 인식", en:"Revenue Recognition", week:10, def:"매출을 언제 잡는가. 장기 계약은 진행/완료 기준 선택 여지. 매출채권 증가율 > 매출 증가율이면 공격적 인식 의심.", hint:"주석 첫 항목" },
{ id:"usefullife", ko:"내용연수", en:"Useful Life", week:10, def:"자산을 감가상각하는 기간. 서버 4년→6년으로 늘리면 이익이 수십 % 오르지만 현금은 그대로. AI 인프라의 GPU 수명 논쟁.", hint:"늘리면 이익↑ 현금 그대로" },
{ id:"capitalization", ko:"자본화", en:"Capitalization (vs Expensing)", week:10, def:"개발비 등을 비용 대신 자산으로 잡는 것. 이익은 올라가고 FCF는 그대로(CapEx로 나감). 공격적 자본화는 이익 과대.", hint:"이익↑ FCF 그대로 → FCF가 정직" },
{ id:"allowance", ko:"충당금", en:"Allowance / Provision", week:10, def:"못 받을 외상·보증·소송 등에 대한 추정 비용. 줄이면 이익이 는다. 충당금 ÷ 매출채권 비율이 갑자기 줄면 의심.", hint:"추정 = 재량" },
{ id:"vie", ko:"변동이익실체", en:"VIE (Variable Interest Entity)", week:10, def:"부채·손실을 연결 밖에 두는 구조. 엔론의 수법. 주석 'VIE', 'Equity method investments'에서 확인.", hint:"장부 밖의 부채" },
{ id:"disclosureworkshop", ko:"공시 해석 워크숍", en:"Disclosure Workshop", week:10, def:"보도자료·Q&A·리스크 팩터 원문을 튜터에 붙여넣어 해부하되, 먼저 스스로 읽고 비교하며 숫자는 원문에서 확인. 동의 않는 부분을 반박하는 것이 실력.", hint:"먼저 읽고, 비교하고, 반박하기" },
{ id:"threewhys", ko:"세 번의 왜", en:"Three Whys", week:10, def:"'이건 왜 그래?'를 세 번 연속 묻기. 세 번째에서 막히는 지점이 진짜 어려운 질문이고 직접 파야 할 곳.", hint:"막히는 곳 = 파야 할 곳" },
// 11주차
{ id:"fedfunds", ko:"기준금리", en:"Fed Funds Rate", week:11, def:"연준이 정하는 초단기 금리. 은행 간 하루짜리. FOMC에서 연 8회 결정.", hint:"연준의 레버" },
{ id:"10year", ko:"10년물 국채 금리", en:"10-Year Treasury Yield", week:11, def:"무위험 수익률의 기준. 주식·부동산 밸류에이션의 기준선. 1%p 오르면 성장주 멀티플 −15~25% 감각.", hint:"자산 가격의 중력" },
{ id:"creditspread", ko:"신용 스프레드", en:"Credit Spread", week:11, def:"회사채 금리 − 국채 금리. 신용 위험의 가격. 넓어지면 시장이 겁먹은 것, 자금 조달 어려움. 좁으면 돈이 쉬운 시기.", hint:"넓어지면 공포" },
{ id:"yieldcurve", ko:"수익률 곡선", en:"Yield Curve", week:11, def:"만기별 금리 그래프. 정상(장기>단기), 역전(단기>장기 — 침체 선행), 가팔라짐(인하 시작 또는 인플레 기대).", hint:"역전 = 침체 선행 지표" },
{ id:"duration", ko:"듀레이션", en:"Duration", week:11, def:"현금흐름이 얼마나 먼 미래에 있는가. 길수록 금리 변화에 민감. 적자 성장주 = 긴 듀레이션 자산.", hint:"먼 미래 = 금리 민감" },
{ id:"cpi", ko:"소비자물가지수", en:"CPI", week:11, def:"소비자 물가 상승률. 헤드라인 vs 근원(식품·에너지 제외). 연준은 근원을 본다.", hint:"근원 CPI" },
{ id:"pce", ko:"개인소비지출 물가", en:"PCE", week:11, def:"연준의 공식 물가 목표 지표. 목표 2%. 근원 PCE가 핵심.", hint:"연준 공식 목표 2%" },
{ id:"fomc", ko:"연방공개시장위원회", en:"FOMC", week:11, def:"연준의 금리 결정 회의. 연 8회. 결정 자체보다 '시장 기대와의 차이'가 시장을 움직인다.", hint:"연 8회 — 기대와의 차이" },
{ id:"qe_qt", ko:"양적완화 / 양적긴축", en:"QE / QT", week:11, def:"QE: 연준이 채권 사서 유동성 공급 → 자산 상승(2020~21). QT: 반대로 회수(2022~). 유동성이 곧 멀티플.", hint:"QE 상승 / QT 압박" },
{ id:"dotplot", ko:"점도표", en:"Dot Plot", week:11, def:"FOMC 위원들의 향후 금리 전망 점. 시장 선물 전망(FedWatch)과의 차이가 서프라이즈 여지.", hint:"연준 전망 vs 시장 전망" },
{ id:"stagflation", ko:"스태그플레이션", en:"Stagflation", week:11, def:"경기 침체 + 인플레. 연준의 이중 책무(물가·고용)가 충돌해 가장 어려운 환경. 거의 모든 자산 손실.", hint:"침체 + 인플레 = 최악" },
{ id:"m2", ko:"M2 통화량", en:"M2 Money Supply", week:11, def:"현금·예금 등 광의 통화량. 증가율이 유동성 지표. 글로벌 M2가 비트코인과 높은 상관.", hint:"돈이 얼마나 있나" },
{ id:"liquidity", ko:"유동성", en:"Liquidity", week:11, def:"시장에 돈이 얼마나 있는가. 자산 가격 = 펀더멘털 × 유동성. 연준 대차대조표·M2·TGA·RRP로 추적.", hint:"같은 이익, 다른 멀티플의 이유" },
{ id:"dxy", ko:"달러 인덱스", en:"DXY", week:11, def:"주요 통화 대비 달러 가치. 강세면 미국 다국적 기업 해외 매출 환산 감소, 신흥국·원자재·비트코인 약세. 한국 투자자는 환율 이중 노출.", hint:"달러 강세 = 해외 매출 감소" },
{ id:"riskonoff", ko:"리스크 온 / 오프", en:"Risk-On / Risk-Off", week:11, def:"돈이 위험자산으로(온) 또는 안전자산으로(오프) 이동. 오프 국면에선 상관관계가 1로 수렴해 분산이 안 통한다.", hint:"오프 = 다 같이 떨어짐" },
{ id:"carrytrade", ko:"캐리 트레이드", en:"Carry Trade", week:11, def:"저금리 통화(엔) 빌려 고수익 자산에 투자. 청산될 때(2024년 8월) 급락.", hint:"엔 캐리 청산 = 급락" },
{ id:"businesscycle", ko:"경기 사이클", en:"Business Cycle", week:11, def:"회복→확장→정점→수축→저점. 주가는 경기보다 6~9개월 선행. 확장 후반(낙관 만연)이 위험, 수축 후반(비관 만연)이 기회.", hint:"주가는 6~9개월 선행" },
{ id:"capacitycycle", ko:"설비 사이클", en:"Capacity Cycle", week:11, def:"자본집약 산업의 순환: 수요↑ → 공급 부족 → 마진↑ → 모두 투자 → 과잉 → 마진 붕괴 → 퇴출 → 다시 부족. 2000년 광케이블, 반도체, AI 인프라.", hint:"마진 최고 = 정점" },
{ id:"creditcycle", ko:"신용 사이클", en:"Credit Cycle", week:11, def:"돈이 쉬울 때 나쁜 프로젝트도 조달 → 과잉 → 경색 → 좋은 프로젝트도 불가 → 완화. 스프레드·IPO·SPAC·벤처 투자로 위치 판단.", hint:"쉬운 돈 → 과잉 → 경색" },
{ id:"cyclicaltrap", ko:"사이클 함정", en:"Cyclical Trap", week:11, def:"이익 정점에서 PER이 낮아 보여 싸다고 착각하는 것. 바닥에서는 PER이 높거나 적자 — 그때가 기회.", hint:"낮은 PER이 정점 신호" },
{ id:"macroexposure", ko:"거시 노출 지도", en:"Macro Exposure Map", week:11, def:"종목별 금리·인플레·달러/유동성·경기 민감도 표. 한 열에 몰려 있으면 종목이 달라도 하나의 베팅.", hint:"종목 수 ≠ 분산" },
{ id:"weeklyroutine", ko:"주간 시장 읽기", en:"Weekly Market Routine", week:11, def:"월요일 숫자 갱신(10분) → 주중 이벤트(10분) → 주말 연결(10분): '이번 주 가장 큰 변화는 X, 내 종목 Y에 경로 Z로 영향, 행동은 없음/조절'.", hint:"30분 — 예측 아닌 노출 관리" },
{ id:"scenarioplanning", ko:"시나리오 계획", en:"Scenario Planning", week:11, def:"금리 2%p 상승, 환율 20% 변동, 침체 — 각 시나리오에서 회사(또는 포트폴리오)가 살아남는지 점검. 예측이 아니라 준비.", hint:"예측 말고 준비" },
// 12주차
{ id:"positionsizing", ko:"포지션 사이징", en:"Position Sizing", week:12, def:"얼마나 살 것인가. 최대 손실(−70% 시 포트폴리오 영향)로 생각하고, 이해도에 비례하며, 상관관계를 세고, 이론 최적의 절반만.", hint:"'무엇을'만큼 '얼마나'" },
{ id:"concentration", ko:"집중 투자", en:"Concentration", week:12, def:"5~10종목에 크게. 깊은 이해가 전제. 현실적 답은 핵심 5~8종목 + 인덱스 기반.", hint:"이해도가 조건" },
{ id:"correlation", ko:"상관관계", en:"Correlation", week:12, def:"자산들이 함께 움직이는 정도. 고성장 기술주 3종목은 '3종목'이 아니라 '고듀레이션 유동성 베팅 1개'. 폭락 시 1로 수렴.", hint:"같은 변수 노출 = 하나의 베팅" },
{ id:"averagingdown", ko:"물타기 vs 추가 매수", en:"Averaging Down", week:12, def:"논지가 유효한데 가격만 떨어졌으면 추가 매수(좋음). 논지가 깨졌는데 단가 낮추려면 물타기(최악). '지금 처음 본다면 사겠는가?'", hint:"논지 유효 여부가 기준" },
{ id:"sellrules", ko:"매도 규칙", en:"Sell Rules", week:12, def:"팔아야 할 때: 논지 깨짐, Bull 가치 초과, 더 좋은 기회, 과대 비중. 팔면 안 되는 이유: 떨어져서, 올라서, 뉴스, 남이 팔아서.", hint:"가격 때문에 팔지 않기" },
{ id:"lossaversion", ko:"손실 회피", en:"Loss Aversion", week:12, def:"손실 고통이 이익 기쁨의 2배. 손실 종목을 못 팔고 이익 종목을 빨리 판다 — '꽃을 뽑고 잡초에 물 주기'.", hint:"꽃 뽑고 잡초에 물" },
{ id:"confirmationbias", ko:"확증 편향", en:"Confirmation Bias", week:12, def:"내 논지를 지지하는 정보만 찾는 것. 방어: 매수 전 가장 강한 약세 논거를 한 페이지 쓰기.", hint:"약세 논거 의무화" },
{ id:"anchoring", ko:"앵커링", en:"Anchoring", week:12, def:"매수 가격·최고가에 묶이는 것. '본전만 오면 판다' — 회사는 당신 매수가를 모른다.", hint:"회사는 내 매수가를 모름" },
{ id:"recencybias", ko:"최신 편향", en:"Recency Bias", week:12, def:"최근 일이 계속될 거라 믿는 것. 상승장 끝에서 사고 하락장 끝에서 판다.", hint:"최근 = 영원 착각" },
{ id:"precommitment", ko:"사전 약속", en:"Pre-commitment", week:12, def:"평온할 때 조건(카드 7번, 폭락 시 행동 규칙)을 미리 써 두고 기계적으로 따르는 것. 편향 방어의 핵심 구조.", hint:"폭락 중엔 못 씀 — 지금 쓰기" },
{ id:"quarterlyreview", ko:"분기 종목 리뷰", en:"Quarterly Review", week:12, def:"종목당 60분: 실적 세트(25) → 숫자 갱신(15) → 사업모델·논지(10) → 밸류에이션(10) → 결정·기록(5). 주 2시간이 경영자 수준 유지의 최소.", hint:"60분 × 종목 수" },
{ id:"investmentjournal", ko:"투자 일지", en:"Investment Journal", week:12, def:"매매마다 이유·기대·감정 기록. 6개월 뒤 읽으면 자기 편향 패턴이 보인다.", hint:"6개월 뒤의 거울" },
{ id:"timebudget", ko:"시간 예산", en:"Time Budget", week:12, def:"매일 10분 카드 + 매주 30분 시장 + 분기 60분/종목. 시간이 부족한 종목은 이해가 얕아지므로 비중을 줄인다.", hint:"시간 없으면 비중 줄이기" },
{ id:"principles", ko:"투자 원칙 문서", en:"Investment Principles", week:12, def:"목적·우위·대상·비대상·사이징·매수·매도·금지 행동·리뷰 주기·위반 시. 평온한 내가 흥분한 미래의 나에게 보내는 지시. 짧고 구체적으로.", hint:"미래의 나에게 보내는 편지" },
{ id:"edge", ko:"우위", en:"Edge", week:12, def:"내가 시장보다 잘 아는 것. 없으면 인덱스가 답. 경영자의 사업 운영 경험은 소비자 사업 유닛 이코노믹스 이해의 우위가 될 수 있다.", hint:"없으면 인덱스" },
{ id:"circleofcompetence", ko:"능력의 범위", en:"Circle of Competence", week:12, def:"버핏: 범위의 크기보다 경계를 아는 것이 중요. 9칸을 채울 수 있는 회사만이 범위 안.", hint:"경계를 아는 것" },
{ id:"graduation", ko:"졸업 점검", en:"Graduation Check", week:12, def:"용어 카드 숙련 80% 이상 + 보유 종목 10개 질문 중 8개를 아무것도 안 보고 5분 안에 답하기. 못 하는 종목은 비중 재검토.", hint:"80% + 8/10" },
{ id:"tenquestions", ko:"10개 질문", en:"Ten Questions", week:12, def:"사업 모델, 마진 4개, 재무 안전성·희석, ROIC·해자, 반영된 기대, 인센티브·자본배분, 핵심 변수, 약세 논거, 판단 변경 조건, CEO에게 던질 질문.", hint:"경영자 수준의 정의" }
]);
