// 금융 용어 플래시카드 — Part 1 (1~6주차 용어)
// 형식: id, ko(한글 용어), en(영문), def(정의·핵심), hint(기억 고리), week(처음 등장하는 주)
window.TERMS = (window.TERMS || []).concat([
// 1주차
{ id:"stock", ko:"주식", en:"Stock / Share", week:1, def:"회사 소유권의 한 조각. 보유 비율만큼 회사의 자산·이익에 대한 잔여 청구권을 가진다.", hint:"간빠맥주를 1,000조각으로 나눈 것" },
{ id:"ipo", ko:"기업공개", en:"IPO (Initial Public Offering)", week:1, def:"회사가 처음으로 주식을 공개 시장에 팔아 자금을 조달하는 것. 이후 거래는 주주 간 손바뀜이라 회사에 돈이 가지 않는다.", hint:"회사가 돈을 받는 유일한 순간" },
{ id:"dividend", ko:"배당", en:"Dividend", week:1, def:"회사가 이익의 일부를 주주에게 현금으로 나눠주는 것. 재투자 수익률이 높은 성장 기업은 보통 배당하지 않는다.", hint:"성장 기업은 안 줌 — 재투자가 더 이득" },
{ id:"shareholder", ko:"주주", en:"Shareholder", week:1, def:"주식을 보유한 사람. 배당·주가 상승·의결권을 얻고, 회사 손실도 자본 범위 내에서 부담한다.", hint:"잔여 청구권자 — 채권자 다음" },
{ id:"marketcap", ko:"시가총액", en:"Market Capitalization", week:1, def:"주가 × 발행주식수. 회사 전체의 시장 가격표. '주가가 싸다'는 무의미하고 시총 대비 이익·현금흐름만 의미가 있다.", hint:"회사를 통째로 사면 얼마?" },
{ id:"ev", ko:"기업가치", en:"Enterprise Value (EV)", week:1, def:"시가총액 + 부채 − 현금. 집값에 딸린 대출까지 포함하듯, 회사를 인수할 때 실제 부담하는 총액.", hint:"시총 + 순부채" },
{ id:"sharesoutstanding", ko:"발행주식수", en:"Shares Outstanding", week:1, def:"현재 시장에 존재하는 주식 총수. 증자·주식보상으로 늘고 자사주 매입으로 준다. 항상 희석 기준(diluted)으로 본다.", hint:"내 지분의 분모" },
{ id:"intrinsicvalue", ko:"내재가치", en:"Intrinsic Value", week:1, def:"회사가 평생 벌어들일 현금을 오늘 가치로 환산한 것. 가격은 매초 바뀌지만 가치는 천천히 변한다.", hint:"가격 ≠ 가치" },
{ id:"marginofsafety", ko:"안전마진", en:"Margin of Safety", week:1, def:"내재가치와 매수 가격의 차이. 가치 100인 회사를 60에 사면 40의 안전마진. 분석이 틀려도 손실을 제한한다.", hint:"그레이엄의 핵심 — 틀려도 덜 잃기" },
{ id:"mrmarket", ko:"미스터 마켓", en:"Mr. Market", week:1, def:"그레이엄의 비유. 매일 다른 기분으로 가격을 제시하는 조울증 동업자. 그의 기분에 휘둘리지 말고 이용하라.", hint:"헐값 부를 때 사고 과열될 때 팔기" },
{ id:"index", ko:"지수", en:"Index", week:1, def:"시장을 대표하는 종목 묶음의 가격 지표. S&P 500·나스닥 100은 시총 가중이라 빅테크 몇 개가 지수를 좌우한다.", hint:"S&P 500 상위 10개 = 30%+" },
{ id:"etf", ko:"상장지수펀드", en:"ETF", week:1, def:"지수를 복제한 펀드를 주식처럼 거래하는 것. 개별 종목 투자자에게는 성과를 비교할 벤치마크.", hint:"QQQ를 못 이기면 시간 낭비" },
{ id:"benchmark", ko:"벤치마크", en:"Benchmark", week:1, def:"내 성과를 비교하는 기준 지수. 미국 기술주 투자자라면 QQQ 또는 S&P 500.", hint:"비교하지 않으면 실력을 모름" },
{ id:"passive", ko:"패시브 투자", en:"Passive Investing", week:1, def:"지수를 그대로 따르는 투자. 시장 거래량의 큰 부분을 차지해 지수 편입·제외 시 기계적 매매가 발생한다.", hint:"지수 편입 = 자동 매수" },
{ id:"volatility", ko:"변동성", en:"Volatility", week:1, def:"가격이 얼마나 출렁이는가. 교과서적 위험이지만 버핏의 위험(영구 손실)과 다르다. 견딜 수 있으면 위험이 아니다.", hint:"출렁임 ≠ 사라짐" },
{ id:"permanentloss", ko:"영구적 자본 손실", en:"Permanent Loss of Capital", week:1, def:"돈이 사라져서 돌아오지 않는 것. 회사 파산, 레버리지 청산, 공포에 바닥에서 파는 것. 진짜 위험.", hint:"버핏의 위험 정의" },
{ id:"compounding", ko:"복리", en:"Compounding", week:1, def:"수익이 수익을 낳는 것. 연 15%면 10년 4배, 20년 16배. 복리의 적은 큰 손실 — −50%는 +100%가 필요.", hint:"−50% 회복엔 +100%" },
{ id:"leverage", ko:"레버리지", en:"Leverage", week:1, def:"빚으로 투자 규모를 키우는 것. 변동성을 영구 손실로 바꾸는 기계. 부채가 많은 회사는 자산 가치의 작은 변화가 자본에 크게 증폭된다.", hint:"변동성 → 영구 손실 변환기" },
// 2주차
{ id:"incomestatement", ko:"손익계산서", en:"Income Statement", week:2, def:"일정 기간 동안 얼마를 벌고 썼는지 보여주는 표. 매출 → 매출총이익 → 영업이익 → 순이익. '기간'의 성적표.", hint:"성적표 (기간)" },
{ id:"balancesheet", ko:"재무상태표", en:"Balance Sheet", week:2, def:"특정 시점에 무엇을 갖고(자산) 누구 돈으로 샀는지(부채+자본) 보여주는 표. 자산 = 부채 + 자본.", hint:"건강검진 (시점)" },
{ id:"cashflowstatement", ko:"현금흐름표", en:"Cash Flow Statement", week:2, def:"현금이 실제로 어디서 들어와 어디로 나갔는지 영업·투자·재무 세 구역으로 보여주는 표. 이익은 의견, 현금은 사실.", hint:"통장 내역 (기간)" },
{ id:"10k", ko:"10-K", en:"Form 10-K", week:2, def:"미국 상장사의 연간 보고서. 법적 책임 하에 작성된 유일한 종합 문서. 10-Q는 분기, 8-K는 수시 공시.", hint:"연간 / 10-Q 분기 / 8-K 수시" },
{ id:"revenue", ko:"매출", en:"Revenue / Sales", week:2, def:"제품·서비스를 제공하고 받기로 한 돈. 발생주의라 외상도 매출. 가격 × 수량으로 분해하고 사업부문별로 봐야 한다.", hint:"받기로 한 돈 ≠ 받은 돈" },
{ id:"accrual", ko:"발생주의", en:"Accrual Accounting", week:2, def:"현금 수수 시점이 아니라 거래 발생 시점에 수익·비용을 인식하는 원칙. 외상 판매도 매출, 공장 구입도 감가상각으로 나눠 비용 처리.", hint:"그래서 이익 ≠ 현금" },
{ id:"segment", ko:"사업부문", en:"Segment", week:2, def:"회사 매출·이익을 사업 단위별로 나눈 것. 10-K 주석 'Segment Information'에서 확인. 어느 부문이 크고 있는지가 핵심.", hint:"테슬라: 자동차 / 에너지 / 서비스" },
{ id:"yoy", ko:"전년 동기 대비", en:"YoY (Year over Year)", week:2, def:"작년 같은 기간과 비교한 성장률. 계절성을 제거한다. QoQ(전분기 대비)는 가속·감속 감지용.", hint:"성장률의 방향(가속/감속)이 주가를 움직임" },
{ id:"recurringrevenue", ko:"반복 매출", en:"Recurring Revenue", week:2, def:"구독·유지보수처럼 계약에 따라 반복적으로 들어오는 매출. 일회성 매출보다 예측 가능하고 높은 가치를 받는다.", hint:"매출의 '질'" },
{ id:"cogs", ko:"매출원가", en:"COGS (Cost of Goods Sold)", week:2, def:"제품·서비스를 만드는 데 직접 들어간 비용. 부품·공장 인건비·서버비. 매출에서 첫 번째로 빼는 것.", hint:"직접 비용" },
{ id:"grossprofit", ko:"매출총이익", en:"Gross Profit", week:2, def:"매출 − 매출원가. 회사가 성장(R&D·마케팅)에 쓸 수 있는 돈의 원천.", hint:"성장 자금의 원천" },
{ id:"grossmargin", ko:"매출총이익률", en:"Gross Margin", week:2, def:"매출총이익 ÷ 매출. 사업의 본질적 경제성. 소프트웨어 80%, 애플 45%, 테슬라 18~20%, 항공 10%대. 추세가 가격 결정력을 말해준다.", hint:"소프트웨어 80 / 제조 20" },
{ id:"opex", ko:"영업비용", en:"Operating Expenses (OpEx)", week:2, def:"제품 제조와 직접 관련 없지만 사업 운영에 드는 비용. R&D, 영업·마케팅(S&M), 일반관리(G&A).", hint:"R&D + S&M + G&A" },
{ id:"operatingincome", ko:"영업이익", en:"Operating Income (EBIT)", week:2, def:"매출총이익 − 영업비용. 이자·세금·일회성 전의 본업 실력. 비트코인 평가손익 같은 사업 외 항목이 빠져 있어 비교에 좋다.", hint:"본업의 실력" },
{ id:"operatingmargin", ko:"영업이익률", en:"Operating Margin", week:2, def:"영업이익 ÷ 매출. 본업 운영 효율. 성장 소프트웨어는 영업 레버리지로 몇 년 만에 −20%에서 +30%로 바뀌기도 한다.", hint:"팔란티어 2023~24의 전환" },
{ id:"operatingleverage", ko:"영업 레버리지", en:"Operating Leverage", week:2, def:"매출이 늘 때 고정비 성격의 영업비용은 덜 늘어 영업이익이 매출보다 빠르게 느는 현상. 반대로 매출이 줄면 이익이 더 빨리 준다.", hint:"매출 +20% → 영업이익 +50%" },
{ id:"sbc", ko:"주식보상비용", en:"Stock-Based Compensation (SBC)", week:2, def:"직원 급여를 주식·옵션으로 주는 것. 현금은 안 나가지만 주주 지분이 희석되는 실질 비용. Non-GAAP에서 흔히 제외되므로 반드시 따로 본다.", hint:"현금 안 나가지만 진짜 비용" },
{ id:"nongaap", ko:"비GAAP 지표", en:"Non-GAAP Metrics", week:2, def:"회사가 주식보상·구조조정 등을 빼고 '조정'한 이익. 회계기준(GAAP)과 차이가 크면 그 원인을 확인해야 한다.", hint:"회사가 보여주고 싶은 숫자" },
{ id:"netincome", ko:"순이익", en:"Net Income", week:2, def:"영업이익에서 이자·기타 손익·세금을 뺀 최종 이익. 일회성·평가손익·세율 변화에 흔들리므로 영업이익과 FCF를 함께 본다.", hint:"회계의 결과물 — 함정 4가지" },
{ id:"eps", ko:"주당순이익", en:"EPS (Earnings Per Share)", week:2, def:"순이익 ÷ 발행주식수. 내 조각 하나가 번 돈. 자사주 매입으로 순이익 없이도 오를 수 있다.", hint:"분모(주식수)를 항상 확인" },
{ id:"dilutedeps", ko:"희석 주당순이익", en:"Diluted EPS", week:2, def:"옵션·전환사채가 모두 주식으로 바뀐다고 가정한 EPS. 기본 EPS보다 보수적이며 항상 이것을 본다.", hint:"항상 희석 기준" },
{ id:"consensus", ko:"컨센서스", en:"Consensus Estimate", week:2, def:"애널리스트 추정치의 평균. 시장의 공식 기대치. 실적이 이를 '비트'했는지 '미스'했는지에 주가가 반응한다.", hint:"시장 기대의 대리 지표" },
{ id:"buyback", ko:"자사주 매입", en:"Share Buyback", week:2, def:"회사가 자기 주식을 사서 소각·보유하는 것. 주식수가 줄어 EPS가 오른다. 주가가 내재가치보다 쌀 때만 주주가치를 창조한다.", hint:"쌀 때 하면 최고, 비쌀 때 하면 최악" },
// 3주차
{ id:"asset", ko:"자산", en:"Assets", week:3, def:"회사가 가진 것. 유동자산(현금·매출채권·재고)과 비유동자산(설비·무형자산·영업권). 자산 = 부채 + 자본.", hint:"왼쪽 — 가진 것" },
{ id:"liability", ko:"부채", en:"Liabilities", week:3, def:"갚아야 할 의무. 유동부채(매입채무·단기차입·선수금)와 비유동부채(장기차입·회사채·리스). 고정된 청구권.", hint:"오른쪽 위 — 남의 돈" },
{ id:"equity", ko:"자본", en:"Shareholders' Equity", week:3, def:"자산 − 부채. 주주의 몫이자 잔여분. 납입자본 + 이익잉여금 − 자사주. 자산 가치 변화가 전부 여기에 반영된다.", hint:"오른쪽 아래 — 내 돈 (잔여)" },
{ id:"currentasset", ko:"유동자산", en:"Current Assets", week:3, def:"1년 안에 현금화 가능한 자산. 현금·단기투자·매출채권·재고.", hint:"1년 내 현금" },
{ id:"deferredrevenue", ko:"이연수익(선수금)", en:"Deferred Revenue", week:3, def:"고객에게 먼저 받았지만 아직 서비스를 제공하지 않아 부채로 잡힌 돈. 구독 사업에서 늘어나면 좋은 신호(현금 선입).", hint:"먼저 받은 돈 = 부채지만 좋은 부채" },
{ id:"netcash", ko:"순현금", en:"Net Cash", week:3, def:"현금 + 단기투자 − 총차입금. 플러스면 순현금, 마이너스면 순부채. 생존 분석의 첫 숫자.", hint:"망하지 않는가?" },
{ id:"currentratio", ko:"유동비율", en:"Current Ratio", week:3, def:"유동자산 ÷ 유동부채. 1 이하면 단기 자금 압박 가능. 단, 고객 돈을 먼저 받는 사업(아마존)은 1 이하도 건강.", hint:"1년 내 갚을 돈 vs 1년 내 현금화" },
{ id:"debttoequity", ko:"부채비율", en:"Debt-to-Equity", week:3, def:"부채 ÷ 자본. 산업마다 정상 범위가 다르다. 유틸리티·은행은 높고 소프트웨어는 낮다. 동종 비교로만 의미.", hint:"산업별 정상 범위 다름" },
{ id:"interestcoverage", ko:"이자보상배율", en:"Interest Coverage", week:3, def:"영업이익 ÷ 이자비용. 3배 이하면 경고, 1배 이하면 본업으로 이자도 못 낸다.", hint:"3 이하 경고 / 1 이하 위험" },
{ id:"burnrate", ko:"현금 소진율", en:"Burn Rate", week:3, def:"적자 기업이 매월 잃는 현금. 런웨이 계산의 분모.", hint:"월간 현금 손실" },
{ id:"runway", ko:"런웨이", en:"Runway", week:3, def:"현금 ÷ 월간 소진액 = 버틸 수 있는 개월 수. 12개월 이하면 곧 증자(희석)나 차입이 온다.", hint:"12개월 이하 → 희석 예고" },
{ id:"workingcapital", ko:"운전자본", en:"Working Capital", week:3, def:"매출채권 + 재고 − 매입채무. 사업을 굴리기 위해 항상 묶여 있는 돈. 성장하면 함께 늘어 현금을 빨아들인다.", hint:"성장 기업이 흑자인데 현금 마르는 이유" },
{ id:"ccc", ko:"현금전환주기", en:"Cash Conversion Cycle (CCC)", week:3, def:"재고일수 + 매출채권일수 − 매입채무일수. 원자재 사서 돈 받을 때까지 걸리는 날. 마이너스면 성장할수록 현금이 늘어난다(아마존, 구독).", hint:"간빠맥주 = −23일 (현금장사)" },
{ id:"receivables", ko:"매출채권", en:"Accounts Receivable", week:3, def:"팔았지만 아직 못 받은 돈. 매출보다 빨리 늘면 밀어내기 판매나 회수 문제 의심.", hint:"외상 판 것" },
{ id:"inventory", ko:"재고", en:"Inventory", week:3, def:"팔려고 보유한 제품·원자재. 매출보다 빨리 늘면 안 팔리고 있다는 신호.", hint:"매출보다 빨리 늘면 경고" },
{ id:"payables", ko:"매입채무", en:"Accounts Payable", week:3, def:"공급자에게 아직 안 준 돈. 길수록 협상력이 강한 것. 애플·아마존은 100일+.", hint:"외상 산 것 = 공짜 자금" },
{ id:"intangible", ko:"무형자산", en:"Intangible Assets", week:3, def:"특허·브랜드·소프트웨어 등 형태 없는 자산. 직접 만든 것은 비용 처리되어 장부에 없고, 인수한 것만 잡힌다. 기술주 장부가치가 과소평가되는 이유.", hint:"자체 개발 = 장부에 없음" },
{ id:"goodwill", ko:"영업권", en:"Goodwill", week:3, def:"다른 회사를 장부가보다 비싸게 인수했을 때 그 차액. 현금화 불가. 자본의 50% 이상이면 인수로 커진 회사.", hint:"인수 프리미엄의 흔적" },
{ id:"impairment", ko:"손상차손", en:"Impairment", week:3, def:"영업권·자산 가치가 기대에 못 미쳐 장부가를 깎는 것. 과거 인수 실패의 뒤늦은 회계적 고백.", hint:"과거 실수의 고백" },
{ id:"bookvalue", ko:"장부가치", en:"Book Value", week:3, def:"재무상태표상 자본. 무형자산 중심 기업에서는 실제 가치를 크게 과소평가하므로 PBR이 무의미하다.", hint:"기술주엔 무의미" },
{ id:"ppe", ko:"유형자산", en:"PP&E (Property, Plant & Equipment)", week:3, def:"공장·설비·데이터센터 등. 자본집약적 사업의 핵심 자산. 감가상각으로 비용화된다.", hint:"테슬라·AI 인프라의 핵심" },
{ id:"dilution", ko:"희석", en:"Dilution", week:3, def:"발행주식수가 늘어 기존 주주의 지분 비율이 줄어드는 것. 증자·주식보상·전환사채·ATM이 원인. 연 4%가 10년이면 32%.", hint:"내 조각이 얇아짐" },
{ id:"convertible", ko:"전환사채", en:"Convertible Bond (CB)", week:3, def:"주식으로 바꿀 수 있는 채권. 주가가 오르면 전환되어 희석, 안 오르면 갚아야 하는 부채. BTC 재무기업의 주요 조달 수단.", hint:"오르면 희석, 안 오르면 빚" },
{ id:"atm", ko:"ATM 발행", en:"At-the-Market Offering", week:3, def:"시장에서 조금씩 계속 신주를 파는 방식. 비트코인 매입 기업들의 주요 자금원. 주가 프리미엄이 있을 때 유리.", hint:"조금씩 계속 파는 증자" },
{ id:"navpremium", ko:"NAV 프리미엄", en:"NAV Premium / mNAV", week:3, def:"시총 ÷ 보유 자산(코인) 가치. 1 이상이면 주식 발행으로 코인을 사서 주당 코인을 늘릴 수 있고, 1 이하면 그 엔진이 멈춘다.", hint:"BTC 재무기업의 엔진" },
// 4주차
{ id:"cfo", ko:"영업활동 현금흐름", en:"Cash Flow from Operations (CFO)", week:4, def:"본업에서 실제로 들어오고 나간 현금. 순이익 + 비현금 항목 ± 운전자본 변동. 건강한 회사는 CFO > 순이익.", hint:"본업 현금 — 순이익보다 커야 정상" },
{ id:"cfi", ko:"투자활동 현금흐름", en:"Cash Flow from Investing (CFI)", week:4, def:"설비·다른 회사 사고 판 현금. 보통 마이너스(투자 중). CapEx가 여기 있다.", hint:"보통 마이너스" },
{ id:"cff", ko:"재무활동 현금흐름", en:"Cash Flow from Financing (CFF)", week:4, def:"빌리고 갚고, 증자하고 배당·자사주 산 현금. 경영진의 자본배분 철학이 드러나는 곳.", hint:"주주를 어떻게 대하는가" },
{ id:"accrualvscash", ko:"이익과 현금의 차이", en:"Earnings vs Cash", week:4, def:"'이익은 의견, 현금은 사실.' 발생주의 이익은 회계 판단이 개입되지만 현금은 조작이 어렵다. 차이가 계속 벌어지면 이익의 질 의심.", hint:"차이의 원인 = 운전자본·D&A·SBC" },
{ id:"da", ko:"감가상각", en:"Depreciation & Amortization (D&A)", week:4, def:"설비·무형자산 구입 비용을 사용 기간에 나눠 비용 처리하는 것. 현금은 안 나가므로 CFO 계산 시 더한다. 내용연수를 늘리면 이익이 는다.", hint:"현금 안 나가는 비용 / 유지 CapEx의 근사치" },
{ id:"cashconversion", ko:"현금전환율", en:"Cash Conversion", week:4, def:"CFO ÷ 순이익. 100% 이상이 정상. 80% 이하가 지속되면 이익의 질에 구조적 문제.", hint:"100% 이상 정상" },
{ id:"noncash", ko:"비현금 항목", en:"Non-Cash Items", week:4, def:"감가상각·주식보상·평가손익·이연법인세처럼 이익에는 반영되지만 현금은 움직이지 않는 항목. CFO 계산에서 되돌린다.", hint:"순이익 → CFO 조정 항목" },
{ id:"fcf", ko:"잉여현금흐름", en:"Free Cash Flow (FCF)", week:4, def:"CFO − CapEx. 사업 유지·확장 후 주주에게 진짜 남는 돈. 기업가치의 근원. SBC를 빼고 다시 계산하는 습관.", hint:"베조스가 유일하게 말한 숫자" },
{ id:"capex", ko:"자본적 지출", en:"Capital Expenditure (CapEx)", week:4, def:"설비·공장·데이터센터에 쓴 현금. 유지 CapEx(≈D&A)와 성장 CapEx로 나뉜다. D&A의 2~3배면 공격적 확장.", hint:"CapEx ÷ D&A = 자본집약도" },
{ id:"fcfmargin", ko:"FCF 마진", en:"FCF Margin", week:4, def:"FCF ÷ 매출. 소프트웨어 25~35%, 제조 5~10%. 진짜 남는 돈의 비율.", hint:"소프트웨어 30 / 제조 5~10" },
{ id:"fcfyield", ko:"FCF 수익률", en:"FCF Yield", week:4, def:"FCF ÷ 시총. 국채 금리와 직접 비교 가능. 5%면 회사를 통째로 사면 연 5% 현금이 나온다는 뜻.", hint:"국채 금리와 비교" },
{ id:"maintenancecapex", ko:"유지 CapEx", en:"Maintenance CapEx", week:4, def:"현재 규모를 유지하는 데 필요한 설비 투자. 대략 감가상각액. 이를 넘는 부분이 성장 CapEx.", hint:"≈ D&A" },
{ id:"capitalallocation", ko:"자본배분", en:"Capital Allocation", week:4, def:"회사가 만든 현금을 재투자·인수·부채상환·배당·자사주 5가지 중 어디에 보낼지 정하는 것. 장기 주주 수익을 결정하는 경영자의 핵심 역할.", hint:"5가지 선택지의 기대수익률 비교" },
{ id:"shareholderyield", ko:"주주환원율", en:"Shareholder Yield", week:4, def:"(배당 + 자사주 매입) ÷ FCF. 성숙 기업은 100%에 가깝고 성장 기업은 0%. 둘 다 정당할 수 있다.", hint:"FCF 중 돌려주는 비율" },
{ id:"netbuyback", ko:"순자사주매입", en:"Net Buyback", week:4, def:"자사주 매입 − 주식보상 발행. 매입보다 발행이 크면 실제로는 희석. 주식수 추세가 답이다.", hint:"매입 80 − 발행 100 = 순희석 20" },
{ id:"capitalintensity", ko:"자본집약도", en:"Capital Intensity", week:4, def:"매출 대비 얼마나 많은 설비 투자가 필요한가. CapEx ÷ 매출 또는 CapEx ÷ D&A. 높을수록 FCF가 늦게 나온다.", hint:"팔란티어 2% vs 네오클라우드 100%+" },
{ id:"qualityofearnings", ko:"이익의 질", en:"Quality of Earnings", week:4, def:"회계 이익이 얼마나 현금으로 뒷받침되는가. CFO > 순이익, 일회성 적음, 회계 재량 적음이 높은 질.", hint:"현금으로 검증되는 이익" },
// 5주차
{ id:"ebitda", ko:"EBITDA", en:"EBITDA", week:5, def:"영업이익 + 감가상각. 이자·세금·설비 투자 전 현금 창출력. 자본집약 기업이 좋아하지만 감가상각을 무시하므로 FCF와 함께 봐야 한다.", hint:"버핏: 감가상각이 비용 아니라는 경영진 믿지 말라" },
{ id:"netmargin", ko:"순이익률", en:"Net Margin", week:5, def:"순이익 ÷ 매출. 최종 마진. 이자·세금·일회성이 반영되어 본업 비교에는 영업이익률이 낫다.", hint:"최종 마진" },
{ id:"margincascade", ko:"마진의 층위", en:"Margin Cascade", week:5, def:"매출총이익률 → 영업이익률 → 순이익률 → FCF 마진의 층. 층 사이 간격이 어디서 돈이 새는지 말해준다.", hint:"간격이 이야기" },
{ id:"roe", ko:"자기자본이익률", en:"ROE (Return on Equity)", week:5, def:"순이익 ÷ 자본. 주주 돈으로 얼마를 벌었나. 15% 이상 우수. 자사주 매입·부채로 왜곡되므로 듀폰 분해와 ROIC를 함께 본다.", hint:"15% 우수 / 20% 탁월" },
{ id:"dupont", ko:"듀폰 분해", en:"DuPont Analysis", week:5, def:"ROE = 순이익률 × 자산회전율 × 재무 레버리지. 같은 ROE라도 엔진이 다르다. 레버리지로 만든 ROE가 가장 위험.", hint:"마진 × 회전 × 레버리지" },
{ id:"assetturnover", ko:"자산회전율", en:"Asset Turnover", week:5, def:"매출 ÷ 총자산. 자산이 얼마나 열심히 일하나. 유통 2~4, 소프트웨어 0.5~1. 간빠맥주 5평 매장 = 회전율 전략.", hint:"작은 자산으로 많은 매출" },
{ id:"financialleverage", ko:"재무 레버리지", en:"Financial Leverage", week:5, def:"총자산 ÷ 자본. 부채로 자산을 얼마나 키웠나. 은행 12배, 소프트웨어 1~2배.", hint:"듀폰의 세 번째 엔진" },
{ id:"roic", ko:"투하자본이익률", en:"ROIC (Return on Invested Capital)", week:5, def:"NOPAT ÷ 투하자본. 사업에 들어간 모든 돈이 얼마를 벌었나. 자본구조에 왜곡되지 않는 경영자의 진짜 성적표. WACC보다 높을 때만 가치 창조.", hint:"ROIC > WACC일 때만 성장이 좋다" },
{ id:"nopat", ko:"세후영업이익", en:"NOPAT", week:5, def:"영업이익 × (1 − 세율). ROIC의 분자.", hint:"영업이익에서 세금만 뺀 것" },
{ id:"investedcapital", ko:"투하자본", en:"Invested Capital", week:5, def:"순운전자본 + 순유형자산 + 무형자산. 사업에 실제로 묶인 돈. ROIC의 분모.", hint:"사업에 묶인 모든 돈" },
{ id:"wacc", ko:"가중평균자본비용", en:"WACC", week:5, def:"주주 요구수익률과 채권자 이자율의 가중평균. 대략 8~11%. ROIC가 이보다 높아야 가치 창조. DCF의 할인율.", hint:"8~11% — 넘어야 가치 창조" },
{ id:"incrementalroic", ko:"증분 ROIC", en:"Incremental ROIC", week:5, def:"새로 투자한 돈이 새로 번 이익 ÷ 새로 투자한 돈. 평균보다 미래를 말해준다. AI 인프라 기업의 핵심 질문.", hint:"GPU 1,000억 → NOPAT 얼마?" },
{ id:"dso", ko:"매출채권회수일수", en:"DSO (Days Sales Outstanding)", week:5, def:"매출채권 ÷ 매출 × 365. 돈 받는 데 며칠. 늘어나면 밀어내기 판매나 회수 문제.", hint:"5일 늘면 매출 1.4% 현금 증발" },
{ id:"dpo", ko:"매입채무지급일수", en:"DPO (Days Payable Outstanding)", week:5, def:"매입채무 ÷ 매출원가 × 365. 공급자에게 돈 주기까지 며칠. 길수록 협상력.", hint:"애플·아마존 100일+" },
{ id:"quickratio", ko:"당좌비율", en:"Quick Ratio", week:5, def:"(유동자산 − 재고) ÷ 유동부채. 재고를 못 판다고 가정한 보수적 유동성.", hint:"유동비율에서 재고 뺀 것" },
{ id:"netdebtebitda", ko:"순부채/EBITDA", en:"Net Debt / EBITDA", week:5, def:"채권자가 가장 많이 보는 레버리지 지표. 3배 이상 부담, 5배 이상 위험(하이일드).", hint:"3 부담 / 5 위험" },
{ id:"cagr", ko:"연평균 성장률", en:"CAGR", week:5, def:"여러 해의 성장을 매년 같은 비율로 환산한 것. 3년 CAGR과 최근 분기 YoY를 함께 보면 추세와 현재 속도를 안다.", hint:"복리 기준 연평균" },
{ id:"screening", ko:"15분 스캔", en:"Quick Screen", week:5, def:"시총·EV, 성장률, 마진 3개, FCF 마진, ROIC, CapEx/D&A, 순현금, 희석률 — 10개 숫자로 회사의 체형을 파악하고 한 줄 결론을 내는 루틴. 매수 결정이 아니라 어디를 팔지 정하는 것.", hint:"10개 숫자 → 한 줄 결론" },
// 6주차
{ id:"organicgrowth", ko:"유기적 성장", en:"Organic Growth", week:6, def:"인수 효과를 뺀 본업의 성장률. 인수로 붙인 매출은 돈 주고 산 것이다.", hint:"인수 빼고 본업만" },
{ id:"expansionrevenue", ko:"확장 매출", en:"Expansion Revenue", week:6, def:"기존 고객이 더 쓰는 데서 오는 매출. 획득 비용이 거의 없어 가장 질 높은 성장.", hint:"기존 고객 추가 구매 = 최고 품질 성장" },
{ id:"growthdeceleration", ko:"성장 감속", en:"Growth Deceleration", week:6, def:"성장률의 방향이 꺾이는 것. 30%→25%는 여전히 고성장이지만 시장은 2차 미분(방향)에 반응해 주가가 떨어질 수 있다.", hint:"성장률의 방향이 주가를 움직임" },
{ id:"arr", ko:"연간 반복 매출", en:"ARR (Annual Recurring Revenue)", week:6, def:"현재 계약된 구독을 1년치로 환산. 매출보다 앞서는 '현재 속도'. ARR 성장률 > 매출 성장률이면 가속 중.", hint:"구독의 현재 속도" },
{ id:"nrr", ko:"순매출유지율", en:"NRR (Net Revenue Retention)", week:6, def:"1년 전 고객들이 올해 쓰는 금액 ÷ 1년 전 금액. 120%면 신규 없이도 20% 성장. 95%면 밑 빠진 독. 제품이 고객 안에서 자라는 힘.", hint:"120%+ 최상위 / 간빠맥주 재방문율의 SaaS 버전" },
{ id:"churn", ko:"이탈률", en:"Churn Rate", week:6, def:"기간 내 떠난 고객 비율. 월 2%면 연 22%, 고객 수명 50개월. LTV의 핵심 가정.", hint:"수명 = 1 ÷ 이탈률" },
{ id:"rpo", ko:"잔여 이행 의무", en:"RPO (Remaining Performance Obligations)", week:6, def:"계약됐지만 아직 매출로 인식되지 않은 금액. 미래 매출의 저수지. 급증하면 가시성 상승.", hint:"계약 잔고 — 팔란티어가 강조" },
{ id:"magicnumber", ko:"매직넘버", en:"Magic Number", week:6, def:"(분기 ARR 증가 × 4) ÷ 전분기 S&M 비용. 1 이상이면 마케팅 효율적, 0.5 이하면 돈을 태우는 중.", hint:"마케팅 1달러 → ARR 몇 달러" },
{ id:"cac", ko:"고객획득비용", en:"CAC (Customer Acquisition Cost)", week:6, def:"S&M 비용 ÷ 신규 고객 수. 고객 한 명 데려오는 데 드는 돈.", hint:"한 명 데려오는 비용" },
{ id:"ltv", ko:"고객생애가치", en:"LTV (Lifetime Value)", week:6, def:"고객당 연간 매출총이익 × 고객 수명. LTV/CAC 3배 이상이 건강. 수명 가정을 부풀리면 얼마든지 조작 가능.", hint:"LTV/CAC ≥ 3" },
{ id:"paybackperiod", ko:"CAC 회수기간", en:"CAC Payback Period", week:6, def:"CAC ÷ 월간 고객당 총이익. 12개월 이하 우수, 24개월 초과면 자본이 오래 묶임.", hint:"12개월 이하 우수" },
{ id:"uniteconomics", ko:"유닛 이코노믹스", en:"Unit Economics", week:6, def:"고객 한 명·제품 한 개·점포 한 곳 단위의 수익 구조. 좋은데 적자면 의도적 투자, 나쁜데 적자면 커질수록 망한다. 적자 자체는 정보가 아니다.", hint:"아마존 vs 위워크" },
{ id:"ruleof40", ko:"Rule of 40", en:"Rule of 40", week:6, def:"매출 성장률 + FCF 마진 ≥ 40이면 건강한 성장 기업. 성장과 수익성의 교환을 하나의 숫자로 본다. 소프트웨어용.", hint:"성장 + 마진 ≥ 40" },
{ id:"growthprofitabilitytradeoff", ko:"성장·수익성 트레이드오프", en:"Growth vs Profitability Trade-off", week:6, def:"마케팅을 줄이면 마진은 오르고 성장은 떨어진다. 시장이 어느 쪽을 원하는지는 금리에 따라 바뀐다(2021 성장 / 2022 수익성).", hint:"금리가 선호를 바꾼다" },
{ id:"backlog", ko:"수주잔고", en:"Backlog", week:6, def:"계약됐지만 아직 이행·매출화되지 않은 주문 총액. 자본집약 기업의 미래 가시성. 계약 기간과 고객 집중도를 함께 본다.", hint:"AI 인프라: 계약 기간이 생명" },
{ id:"utilization", ko:"가동률", en:"Utilization Rate", week:6, def:"설비가 실제로 쓰이는 비율. 자본집약 사업에서 가동률이 곧 마진. 90% 가동 5년 계약이면 부채도 감당된다.", hint:"자본집약 사업의 마진 = 가동률" },
{ id:"mnav", ko:"mNAV", en:"Multiple of Net Asset Value", week:6, def:"BTC 재무기업의 시총 ÷ 보유 코인 가치. 1 이상이면 주식 발행 → 코인 매입 → 주당 BTC 증가 엔진이 돌고, 1 이하면 멈춘다.", hint:"BTC 재무기업의 유일한 엔진" },
{ id:"regulatorycredit", ko:"규제 크레딧", en:"Regulatory Credits", week:6, def:"배출 규제를 충족 못 하는 자동차사가 테슬라 등에서 사는 크레딧. 원가 0의 매출이라 자동차 마진과 분리해서 봐야 한다.", hint:"테슬라 마진 분석 시 분리" }
]);
